### ISSUE TITLE
UHDAS ADCP has wrong vertical depth because the code reads a wrong file

### ISSUE THREAD

**Issue by Jamie-Hilditch** [Jamie-Hilditch/SUNRISE-data-processing#3]

**Comment by Jamie-Hilditch** [comment]
@fucent @dswinters did we conclude that this actually isn't an issue?

**Comment by Jamie-Hilditch** [comment]
I like Dylan find no difference

**Comment by fucent** [comment]
No, it is not a problem now. I used an earlier version which was wrong.
